# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qb_DMuVu3mGZkEVufXVjeJ5dgV91YlZt
"""

# ==========================================
# Gender Recognition using CNN
# Streamlit App
# ==========================================

# Import Libraries
import streamlit as st
import numpy as np
from PIL import Image
import tensorflow as tf

# ------------------------------------------
# Page Settings
# ------------------------------------------

st.set_page_config(
    page_title="Gender Recognition",
    page_icon="👨",
    layout="centered"
)

# ------------------------------------------
# Load Trained Model
# ------------------------------------------

model = tf.keras.models.load_model("gender_model (1).keras")

# ------------------------------------------
# Title
# ------------------------------------------

st.markdown(
    "<h1 style='text-align:center; color:#1E90FF;'>Gender Recognition using CNN</h1>",
    unsafe_allow_html=True
)

st.write("Upload an image and the model will predict whether the person is **Male** or **Female**.")

st.write("---")

# ------------------------------------------
# Upload Image
# ------------------------------------------

uploaded_file = st.file_uploader(
    "Choose an Image",
    type=["jpg", "jpeg", "png"]
)

# ------------------------------------------
# Prediction
# ------------------------------------------

if uploaded_file is not None:

    # Display Image
    image = Image.open(uploaded_file)

    st.image(image, caption="Uploaded Image", width=300)

    # Resize Image
    image = image.resize((100,100))

    # Convert Image into Array
    img_array = np.array(image)

    # Normalize
    img_array = img_array / 255.0

    # Add Extra Dimension
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    prediction = model.predict(img_array)

    probability = prediction[0][0]

    st.write("---")

    # Display Result
    if probability < 0.5:

        confidence = (1 - probability) * 100

        st.success("Prediction : Male")

        st.info(f"Confidence : {confidence:.2f}%")

    else:

        confidence = probability * 100

        st.success("Prediction : Female")

        st.info(f"Confidence : {confidence:.2f}%")

st.write("---")

st.markdown(
    "<center>Made with ❤️ using Streamlit and TensorFlow</center>",
    unsafe_allow_html=True
)
