# -*- coding: utf-8 -*-
"""tn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQf0olXAxUyITVjv3bp3WUw8j8q2nzbT
"""

# ==========================================
# Gender Recognition using CNN
# Beginner Friendly Training Code
# ==========================================

# Import Libraries
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    GlobalAveragePooling2D,
    Dense
)
import matplotlib.pyplot as plt

# ==========================================
# Dataset Paths
# ==========================================

train_path = "/content/sample_data/Dataset/Train"
validation_path = "/content/sample_data/Dataset/Validation"

# ==========================================
# Image Size and Training Settings
# ==========================================

img_height = 100
img_width = 100

batch_size = 32
epochs = 5

# ==========================================
# Prepare Training Images
# ==========================================

train_datagen = ImageDataGenerator(
    rescale=1/255,
    horizontal_flip=True,
    zoom_range=0.2
)

# ==========================================
# Prepare Validation Images
# ==========================================

validation_datagen = ImageDataGenerator(
    rescale=1/255
)

# ==========================================
# Load Training Dataset
# ==========================================

train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode="binary"
)

# ==========================================
# Load Validation Dataset
# ==========================================

validation_generator = validation_datagen.flow_from_directory(
    validation_path,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode="binary"
)

# Print Class Labels

print("\nClass Labels:")
print(train_generator.class_indices)

# ==========================================
# Create CNN Model
# ==========================================

model = Sequential()

# First Convolution Layer
model.add(
    Conv2D(
        16,
        (3,3),
        activation="relu",
        input_shape=(100,100,3)
    )
)
model.add(MaxPooling2D(pool_size=(2,2)))

# Second Convolution Layer
model.add(
    Conv2D(
        32,
        (3,3),
        activation="relu"
    )
)
model.add(MaxPooling2D(pool_size=(2,2)))

# Third Convolution Layer
model.add(
    Conv2D(
        64,
        (3,3),
        activation="relu"
    )
)
model.add(MaxPooling2D(pool_size=(2,2)))

# Replace Flatten with GlobalAveragePooling
model.add(GlobalAveragePooling2D())

# Hidden Layer
model.add(Dense(32, activation="relu"))

# Output Layer
model.add(Dense(1, activation="sigmoid"))

# ==========================================
# Compile Model
# ==========================================

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Show Model Summary
model.summary()

# ==========================================
# Train the Model
# ==========================================

history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=epochs
)

# ==========================================
# Save Model
# ==========================================

model.save("gender_model (1).keras")

print("\nModel Saved Successfully!")
print("File Name : gender_model (1).keras")

# ==========================================
# Evaluate Model
# ==========================================

loss, accuracy = model.evaluate(validation_generator)

print(f"\nValidation Accuracy : {accuracy * 100:.2f}%")

# ==========================================
# Accuracy Graph
# ==========================================

plt.figure(figsize=(8,5))

plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])

plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.legend(["Training","Validation"])

plt.show()

# ==========================================
# Loss Graph
# ==========================================

plt.figure(figsize=(8,5))

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])

plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend(["Training","Validation"])

plt.show()

print("\nTraining Completed Successfully!")
