# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4BKSYuFYbAaYZmXqYAM6LITnRQANr2W
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Google Play Store Dashboard",
    page_icon="📱",
    layout="wide"
)

# -----------------------------
# Title
# -----------------------------
st.title("📱 Google Play Store Dashboard")
st.markdown("Explore and visualize the Google Play Store dataset.")

# -----------------------------
# Load Dataset
# -----------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("googleplaystore_v2.csv")
    return df

df = load_data()

# -----------------------------
# Data Cleaning
# -----------------------------
df = df.drop_duplicates()

# Convert Rating
if "Rating" in df.columns:
    df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce")

# Convert Reviews
if "Reviews" in df.columns:
    df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")

# Convert Size
if "Size" in df.columns:

    def convert_size(size):
        if pd.isna(size):
            return np.nan

        size = str(size)

        if "M" in size:
            return float(size.replace("M", ""))

        elif "k" in size:
            return float(size.replace("k", "")) / 1024

        else:
            return np.nan

    df["Size"] = df["Size"].apply(convert_size)

# Convert Installs
if "Installs" in df.columns:
    df["Installs"] = (
        df["Installs"]
        .astype(str)
        .str.replace(",", "")
        .str.replace("+", "", regex=False)
    )

    df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

# Convert Price
if "Price" in df.columns:
    df["Price"] = (
        df["Price"]
        .astype(str)
        .str.replace("$", "", regex=False)
    )

    df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("Filters")

categories = sorted(df["Category"].dropna().unique())

selected_category = st.sidebar.selectbox(
    "Select Category",
    ["All"] + list(categories)
)

if selected_category != "All":
    df = df[df["Category"] == selected_category]

# -----------------------------
# Dataset Overview
# -----------------------------
st.header("Dataset Overview")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Apps", len(df))

with col2:
    st.metric(
        "Average Rating",
        round(df["Rating"].mean(), 2)
    )

with col3:
    st.metric(
        "Average Reviews",
        f"{int(df['Reviews'].mean()):,}"
    )

# -----------------------------
# Dataset Preview
# -----------------------------
st.subheader("Dataset Preview")

st.dataframe(df.head())

# -----------------------------
# Missing Values
# -----------------------------
st.subheader("Missing Values")

missing = df.isnull().sum()

st.dataframe(
    missing[missing > 0].sort_values(ascending=False)
)

# -----------------------------
# Rating Distribution
# -----------------------------
st.subheader("Rating Distribution")

fig, ax = plt.subplots(figsize=(8,5))

sns.histplot(
    df["Rating"],
    bins=20,
    kde=True,
    ax=ax
)

ax.set_xlabel("Rating")
ax.set_ylabel("Count")

st.pyplot(fig)

# -----------------------------
# Top Categories
# -----------------------------
st.subheader("Top Categories")

category_counts = (
    df["Category"]
    .value_counts()
    .head(10)
)

fig, ax = plt.subplots(figsize=(10,6))

sns.barplot(
    x=category_counts.values,
    y=category_counts.index,
    ax=ax
)

ax.set_xlabel("Number of Apps")
ax.set_ylabel("Category")

st.pyplot(fig)

# -----------------------------
# Free vs Paid Apps
# -----------------------------
st.subheader("Free vs Paid Apps")

if "Type" in df.columns:

    fig, ax = plt.subplots(figsize=(6,6))

    df["Type"].value_counts().plot(
        kind="pie",
        autopct="%1.1f%%",
        ax=ax
    )

    ax.set_ylabel("")

    st.pyplot(fig)

    # -----------------------------
# Installs vs Rating
# -----------------------------
st.subheader("⭐ Rating vs 📥 Installs")

scatter_df = df.dropna(subset=["Rating", "Installs"])

fig, ax = plt.subplots(figsize=(10,6))

sns.scatterplot(
    data=scatter_df,
    x="Installs",
    y="Rating",
    alpha=0.6,
    ax=ax
)

ax.set_xlabel("Installs")
ax.set_ylabel("Rating")
ax.set_title("Rating vs Installs")

st.pyplot(fig)

# -----------------------------
# Price Distribution
# -----------------------------
st.subheader("💰 Price Distribution")

price_df = df[df["Price"] > 0]

if len(price_df) > 0:

    fig, ax = plt.subplots(figsize=(8,5))

    sns.histplot(
        price_df["Price"],
        bins=20,
        kde=True,
        ax=ax
    )

    ax.set_xlabel("Price ($)")
    ax.set_ylabel("Number of Apps")

    st.pyplot(fig)

else:
    st.info("No paid applications found.")

# -----------------------------
# Correlation Heatmap
# -----------------------------
st.subheader("🔥 Correlation Heatmap")

numeric_df = df.select_dtypes(include=np.number)

if len(numeric_df.columns) > 1:

    fig, ax = plt.subplots(figsize=(8,6))

    sns.heatmap(
        numeric_df.corr(),
        annot=True,
        cmap="coolwarm",
        fmt=".2f",
        ax=ax
    )

    st.pyplot(fig)

# -----------------------------
# Interactive Rating Filter
# -----------------------------
st.subheader("🎯 Filter Apps by Rating")

min_rating = st.slider(
    "Minimum Rating",
    0.0,
    5.0,
    4.0,
    0.1
)

filtered_df = df[df["Rating"] >= min_rating]

st.write(f"Showing **{len(filtered_df)}** apps")

st.dataframe(filtered_df)

# -----------------------------
# Top Rated Apps
# -----------------------------
st.subheader("🏆 Top Rated Apps")

top_apps = (
    filtered_df[
        ["App", "Category", "Rating", "Reviews", "Installs"]
    ]
    .sort_values(
        by="Rating",
        ascending=False
    )
    .head(15)
)

st.dataframe(top_apps)

# -----------------------------
# Download Dataset
# -----------------------------
st.subheader("⬇ Download Filtered Dataset")

csv = filtered_df.to_csv(index=False).encode("utf-8")

st.download_button(
    label="Download CSV",
    data=csv,
    file_name="filtered_googleplaystore.csv",
    mime="text/csv"
)

# -----------------------------
# Dataset Statistics
# -----------------------------
st.subheader("📊 Statistical Summary")

st.dataframe(df.describe())

# -----------------------------
# Footer
# -----------------------------
st.markdown("---")

st.markdown(
    """
    ### 📱 Google Play Store Dashboard

    **Built using**
    - Streamlit
    - Pandas
    - NumPy
    - Matplotlib
    - Seaborn

    Developed for Data Visualization Case Study.
    """
)