# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hn_9WgPU2AQzzgtRgKGChlnrDFpzGMpx
"""

import streamlit as st
import joblib
import cv2
import numpy as np
from PIL import Image

# ------------------------------
# Page Configuration
# ------------------------------
st.set_page_config(
    page_title="Male vs Female Eye Detection",
    page_icon="👁",
    layout="centered"
)

# ------------------------------
# Custom CSS
# ------------------------------
st.markdown("""
<style>
.main{
    background-color:#F5F7FA;
}
h1{
    color:#1565C0;
    text-align:center;
}
.result{
    font-size:28px;
    font-weight:bold;
    color:green;
    text-align:center;
}
.footer{
    text-align:center;
    color:gray;
}
</style>
""", unsafe_allow_html=True)

# ------------------------------
# Load Model
# ------------------------------
model = joblib.load("eye_gender_knn.pkl")

# ------------------------------
# Title
# ------------------------------
st.title("👁 Male vs Female Eye Detection")

st.write("Upload an eye image and the model will predict whether it belongs to a Male or Female.")

# ------------------------------
# Sidebar
# ------------------------------
st.sidebar.header("Project Information")

st.sidebar.info("""
Model : K-Nearest Neighbors (KNN)

Image Size : 64 × 64

Classes:
- Male Eye
- Female Eye
""")

# ------------------------------
# Upload Image
# ------------------------------
uploaded_file = st.file_uploader(
    "Upload Eye Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(image, caption="Uploaded Image", use_container_width=True)

    img = np.array(image)

    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    img = cv2.resize(img, (64,64))

    img = img.flatten().reshape(1,-1)

    prediction = model.predict(img)[0]

    probabilities = model.predict_proba(img)[0]

    confidence = np.max(probabilities) * 100

    if prediction == 0:
        st.success("Prediction : Female Eye 👩")
    else:
        st.success("Prediction : Male Eye 👨")

    st.info(f"Confidence : {confidence:.2f}%")

st.markdown("---")

st.markdown(
"<div class='footer'>Made with ❤️ using Streamlit & Scikit-Learn</div>",
unsafe_allow_html=True
)