# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dT3XiyTGZ4-tFfL4gYcccJREmD-RYpLH
"""

import os
import cv2
import joblib
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# -----------------------------
# Dataset Path
# -----------------------------
DATASET_PATH = "/content/sample_data/Dataset"

IMAGE_SIZE = (64, 64)

X = []
y = []

print("Loading images...")

# Female Images
female_path = os.path.join(DATASET_PATH, "/content/sample_data/Dataset/Femaleeyes")

for img_name in os.listdir(female_path):
    img_path = os.path.join(female_path, img_name)

    img = cv2.imread(img_path)

    if img is None:
        continue

    img = cv2.resize(img, IMAGE_SIZE)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    X.append(img.flatten())
    y.append(0)

# Male Images
male_path = os.path.join(DATASET_PATH, "/content/sample_data/Dataset/Maleeyes")

for img_name in os.listdir(male_path):
    img_path = os.path.join(male_path, img_name)

    img = cv2.imread(img_path)

    if img is None:
        continue

    img = cv2.resize(img, IMAGE_SIZE)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    X.append(img.flatten())
    y.append(1)

X = np.array(X)
y = np.array(y)

print("Total Images :", len(X))

# -----------------------------
# Split Dataset
# -----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training KNN...")

knn = KNeighborsClassifier(
    n_neighbors=5
)

knn.fit(X_train, y_train)

pred = knn.predict(X_test)

acc = accuracy_score(y_test, pred)

print("\nAccuracy :", round(acc * 100, 2), "%")

print("\nClassification Report\n")
print(classification_report(y_test, pred))

joblib.dump(knn, "eye_gender_knn.pkl")

print("\nModel Saved Successfully.")