# -*- coding: utf-8 -*-
"""Employee_Retention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-oLGqN0HClxb4p6xQHkte_lsISjKxyGT

Employee-Retention
"""

import streamlit as st
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Load Dataset
df = pd.read_csv("HR_comma_sep.csv")

# Select useful features
df = df[[
    "satisfaction_level",
    "average_montly_hours",
    "promotion_last_5years",
    "salary",
    "left"
]]

# One Hot Encoding
df = pd.get_dummies(df, columns=["salary"], drop_first=True)

X = df.drop("left", axis=1)
y = df["left"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

st.title("Employee Retention Prediction")

st.write("### Model Accuracy")
st.success(f"{accuracy*100:.2f}%")

st.write("## Enter Employee Details")

satisfaction = st.slider(
    "Satisfaction Level",
    0.0,
    1.0,
    0.5
)

hours = st.slider(
    "Average Monthly Hours",
    80,
    320,
    200
)

promotion = st.selectbox(
    "Promotion in Last 5 Years",
    [0,1]
)

salary = st.selectbox(
    "Salary",
    ["Low","Medium","High"]
)

salary_low = 0
salary_medium = 0

if salary=="Low":
    salary_low=1
elif salary=="Medium":
    salary_medium=1

prediction = model.predict([[
    satisfaction,
    hours,
    promotion,
    salary_low,
    salary_medium
]])

if st.button("Predict"):

    if prediction[0]==0:
        st.success("Employee is likely to stay.")

    else:
        st.error("Employee is likely to leave.")