# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sBTl0G0TeegMAS3dcmJzi-BxMNto4vJp
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

st.set_page_config(
    page_title="Canada Per Capita Income Prediction",
    page_icon="🇨🇦",
    layout="centered"
)

st.title("🇨🇦 Canada Per Capita Income Prediction")
st.write("Predict Canada's per capita income using **Linear Regression**.")

# Load Dataset
df = pd.read_csv("canada_per_capita_income.csv")

# Features and Target
X = df[['year']]
y = df['per capita income (US$)']

# Train Model
model = LinearRegression()
model.fit(X, y)

st.subheader("Dataset")
st.dataframe(df)

# Scatter Plot
fig, ax = plt.subplots(figsize=(8,5))
ax.scatter(df['year'], df['per capita income (US$)'], color='blue', label='Actual Data')
ax.plot(df['year'], model.predict(X), color='red', linewidth=2, label='Regression Line')
ax.set_xlabel("Year")
ax.set_ylabel("Per Capita Income (US$)")
ax.legend()

st.pyplot(fig)

st.subheader("Predict Income")

year = st.number_input(
    "Enter Year",
    min_value=1970,
    max_value=2050,
    value=2020,
    step=1
)

prediction = model.predict([[year]])

st.success(f"Predicted Per Capita Income in {year}: **${prediction[0]:,.2f}**")

st.markdown("---")

st.write("### Model Information")
st.write(f"Intercept : {model.intercept_:.4f}")
st.write(f"Slope : {model.coef_[0]:.4f}")

if year == 2020:
    st.info("Expected Answer ≈ **41288.69 USD**")